### ISSUE TITLE
Release Event Hubs April 2020 update for Python

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#10263]
This is a parent issue tracking the work planned for Event Hubs for the April update.
Code complete date: April 3rd, 2020

## API design 
- [ ] **In Progress** Propose smarter send APIs such that the user doesnt have to one by one fill the `EventDataBatch` to be able to send events
- [ ] **In Progress** Propose API to control greedy claiming of partitions by the Event Processor

## Features
- [x] Receive in batches
- [x] Code sample showing how to convert IotHub connection string to an Event Hubs compatible one which points to the built-in Event Hubs endpoint
- [x] Code sample showing workaround needed for Event Hubs in Azure Stack
- [ ] Receiver Redirect feature
- [ ] Review current logging experience, come up with a plan to streamline and be consistent across languages for ease of customer support, tackle low hanging fruits

cc @YijunXieMS

**Comment by ramya-rao-a** [comment]
The April update which is a preview contained the below
- receive in batches
- Code sample showing workaround needed for Event Hubs in Azure Stack
- Add in missing system properites when reading from Iothub. #10408

Rest of the work is being moved to the May update.

@YijunXieMS, Please provide a link to the April update here and close the issue

**Comment by YijunXieMS** [comment]
Released 5.1.0b1 on 04/06/2020
https://pypi.org/project/azure-eventhub/5.1.0b1/
