### ISSUE TITLE
Release Service Bus Track 2 Library Preview 2 for Python

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#10707]
API Design
- [x] Design and implement Topic functionality
- [x] Design and implement Subscription functionality
- [ ] 🛑 Rule Management:
  - Not in this release, there is a service side issue related to rule management within transaction
- [x] Determine if send should have a timeout given that we have retry options on the client
- [x] Multi-session receiver: https://github.com/Azure/azure-sdk-for-python-pr/issues/492
- [ ] (Stretch) Transaction support
- [ ] 🏃(Stretch) Auto-complete
- [x] (stretch) Smart batching/sending
- [x] (stretch) Scheduling
- [x] (stretch) AutoLockRenew

Features

- [x] Split off SessionReceiver from Receiver
- [x] _open() should not require close() if it fails
- [x] Exception hierarchy improvements
- [x] Migration guide and troubleshooting improvements
- [ ] (Stretch) Revisit double-with call pattern
- [ ] (Stretch) Connection Sharing

Doc Improvement:

- [x] Lily Ma feedback: https://github.com/Azure/azure-sdk-for-python/issues/10693

**Comment by ramya-rao-a** [comment]
azure-servicebus 7.0.0b2 is out: https://pypi.org/project/azure-servicebus/7.0.0b2/

@yunhaoling If #10602 is not completed, please move it to #11234
