### ISSUE TITLE
Release Event Hubs May 2020 update for Python

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#10738]
This is a parent issue tracking the work planned for Event Hubs for the May update.
Code complete date: May 3rd, 2020

## API design 
- [ ] **In Progress** Propose API to control greedy claiming of partitions by the Event Processor
- [ ] SharedKeyCredential

## Features
- [ ] Receiver Redirect feature #10296 
- [x] Smarter send APIs such that the user doesnt have to one by one fill the `EventDataBatch` to be able to send events #9181 
- [x] Reduce tracing debt #9599

cc @YijunXieMS

**Comment by YijunXieMS** [comment]
Released 5.1.0 on 05/04/2020 
https://pypi.org/project/azure-eventhub/5.1.0/
