### ISSUE TITLE
Release Service Bus Track 1 for Python

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#11235]
Bug Fixes

- [x] Address remaining p0 T1 bugs (See linked issues)

Doc Improvement:

- [x] Communicate deprecation plan
- [x] Evangelize 7.0 migration strategy

**Comment by yunhaoling** [comment]
Closing the issue as all the issue have been addressed and the final track1 release [0.50.3](https://pypi.org/project/azure-servicebus/0.50.3/) is out.
