### ISSUE TITLE
Release Service Bus Track 2 Library Preview 3 for Python

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#11234]
This is a parent issue tracking the work planned for Service Bus to release the second preview in June following the [Python Azure SDK guidelines](https://azure.github.io/azure-sdk/python_introduction.html) 

Code complete date: June 5th, 2020

API Design

- [x]  Auto-complete
- [x] Dead Letter Queue support
- [ ] (Stretch) Alternate UAMQP Data Type support

Features
- [x] CRUD & list operations using connection string via the ATOM apis
- [x] (Stretch) Revisit double-with call pattern
- [ ] (Stretch) Connection Sharing

**Comment by KieranBrantnerMagee** [comment]
The followup questions for autocomplete and double-with have been included in our UX study agenda.  Any actions following from that will come in during the July milestone.
