### ISSUE TITLE
[formrecognizer] Arch board issues

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#11283]
* [x] Consider renaming `form_file_stream` and `receipt_file_stream` to be more general like `data` since it accepts file-like object or bytes in memory  #11518 
* [x] Update docstring type to match type hint for recognize input: Union[bytes, IO[bytes]]
* [x] Update samples to take stream as input
* [x] Update samples to show `confidence` on `FormWord`
* [x] Should the `get_client` method move to `FormTrainingClient`? Should we remove it altogether?
**We will move the get_client method to FormTrainingClient**
* [x] Reconsider naming around `CustomFormSubModel`. We want people to understand what this is without having to look at documentation. Tracked in #11389 
* [x] Also reconsider naming for `CustomFormModel.models` attribute. Tracked in #11389 
* [x] Should we enforce guid format for model_id? **No**  #11569 
* [x] Reconsider having `use_training_labels=False` as the default. Possibly make this a required param.  #11529 
* [x] Do we need to reconsider naming of `last_modified`? This assumes it's mutable and it's not. https://github.com/Azure/azure-sdk-for-python/pull/11592
* [ ] Is `receipt_locale` specific enough to differentiate all receipt types? See this issue: https://github.com/azure/azure-sdk-for-net/issues/11912 and consider design for future (Note: receipt_locale won't be exposed in v2.0)

**Comment by iscai-msft** [comment]
Closing, and tracking remaining receipt_locale issue here: https://github.com/Azure/azure-sdk-for-python/issues/11712
