### ISSUE TITLE
[Tables] Azure Tables Epic 1

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#11303]
## Tasks
- [x] Introduction to repos / azure #11297 
- [x] Familiarity with Tables #11298 
- [x] Code generation for Tables #11299 
- [x] Make calls with generated code #11300 

## Deliverables
  - [x] Arch Board: Introduction to Azure Tables service #11301 
  - [x] Stretch: Pseudo code for HERO scenarios #11302
