### ISSUE TITLE
[Tables] Azure Tables Epic 2

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#11313]
## Tasks
- [x] Construct Tables SDK around generated code #11305 
- [x] Add pipeline policies to Tables #11306  
- [x] Support authentication #11308 
- [x] Consider design of parent/child hierarchies #11309 
- [x] Implement async client/methods #11310 
- [x] Plug in test suite for Tables #11311 

## Deliverables
  - [x] Small demo in scrum
  - [x] Generate Tables APIview to review design #11312
