### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 5 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#11336]
This tracks the work to release the Azure Cognitive Search Track2 Preview 5 Library

### API Review
- [ ] Final architecture board review

### Features
- [ ] Search paging << API change
- [x] Change to type constructors << API change
