### ISSUE TITLE
EventGrid - Sprint 1 - Ramp up for prototyping EventGrid Track2

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#11465]
Rampup

- [ ] Familiarize Azure Concepts and tooling
- [ ] Familiarize with EventGrid utilization and their REST API
- [ ] Familiarize with CodeGen
- [ ] Familiarize with Azure Identity
- [ ] Familiarize with Azure Core
- [ ] Review existing SDKs and scenarios.

API Design

- [ ] (Stretch) Identify and enumerate hero scenarios

Deliverables

- [ ] A demo app that plumbs EventGrid together with blob events into a webhook.
- [ ] (Stretch) Pseudo-code for hero scenarios
