### ISSUE TITLE
[formrecognizer] Address Arch Board Feedback

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#11881]
- [ ] follow up if there could be something labeled that is not text when thinking of naming for `FieldText`. Should this be `FieldData` or alternate naming? Otherwise property/model naming difference between languages is okay  **Tracked in** #12274 
- [x] `requested_on` and `completed_on` should be renamed to `training_started_on` and `training_completed_on` #12207 
- [ ] possibly add training duration - need to understand if this is something users want/need  **Tracked in** #12277
- [ ] need to make sure we do support local file paths for containers  **Tracked in** #12276 
- [x] KC doesn't like `submodels` - should we brainstorm naming for the property/model here some more? **Feature team decided "No".**
- [x] KC didn't like `CustomFormModel` and preferred this to be something like `TrainingResult` **Feature team decided "No".**

**Comment by kristapratico** [comment]
Spun off anything pending into new issue, closing this
