### ISSUE TITLE
[formrecognizer] Address Feedback from JS/Java UX Studies

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#11882]
- [x] In unsupervised recognize [sample](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/samples/sample_differentiate_output_models_trained_with_and_without_labels.py#L80), show how to search for a certain field name in the dict  #12164 
- [x] Add to documentation description about what SAS Url is – link to service docs about training (we might already do this) https://github.com/Azure/azure-sdk-for-python/pull/12216
- [ ] Add readme code snippet pointers for statements in key concepts.  **Tracked in** #12275 
- [x] For Copy, hard to find resource id and region. Add docstrings to clarify this more.  https://github.com/Azure/azure-sdk-for-python/pull/12216
_Add in the documentation how/where to get the region for Copy and the list of available regions_
- [x] Consider adding a mix of fromUrl and stream overload code snippets in the main readme. https://github.com/Azure/azure-sdk-for-python/pull/12216
- [x] `text` vs `text_content` – _clarify ref docs_   https://github.com/Azure/azure-sdk-for-python/pull/12216
- [x] Make sure sync and async links are clearly represented in samples list - _All language to cross-check_  https://github.com/Azure/azure-sdk-for-python/pull/12216
- [x] strongly typed receipt sample #12128 

To follow up:
- [ ] Should consider having a `getRow()` or similar not natural to have a `getCells()` and diving into the cell information to find the row it belongs to. Also, it could use a better data structure here. [constant pain point to get to the field] - _Follow up (Mariana/Anne) Table indexer issue - https://github.com/Azure/azure-sdk-for-net/issues/9975_ and **Tracked in** #10894 
- [ ] 2/5 users attempted and were hopeful that they could pass in the local File URL for the `fromUrl` and that should have worked. Circling back to if we should consider adding an overload that takes in a file input.  - _(Waiting to know Johan's thoughts, Issue - https://github.com/Azure/azure-sdk-for-java/issues/12402#issue-643410189)_   **Tracked in** #12276 
- [ ] Add documentation to clarify getFieldValue() and getValueText() (note: not python naming) - 
_Deferred discussion to Architecture board. Consider if renaming fields to `labelData` or `labelTextInformation` should help ?_  **Tracked in** #12274

**Comment by rakshith91** [comment]
Some initial feedback from Java/JS UX study

- [ ] Add documentation to clarify getFieldValue() and getValueText()
	
- [ ] Order fields in position for the document (unsupervised map of fields). Currently, field ordering is not maintained.	

- [ ] Helper function to search and return fields to shortcut getFields().get("FieldName") (Might need more discussion).

- [ ] Helper/accessor to get Table cell data more easily (Table indexer or getRow() like Js has)

- [ ] [Service follow up] Cannot understand the breaking for FormLines. For a line "* = Exceeds Maximum: Indicates the service exceeds patient/group benefit year maximum." why is it breaking on "=" or "*" 

- [ ] Models exposed to users to have toString() method for formatting purposes.	

- [ ] Add readme code snippet pointers for statements in key concepts.	

- [ ] For Copy, hard to find resource id and region. Add docstrings to clarify this more.	

- [ ] Consider adding a mix of fromUrl and stream overload code snippets in the main readme.

- [ ] Consider adding a sample showing an example for converting a recognized form to known predefined fields. [receipt sample]

- [ ] Consider moving TrainingDoucments errors to top level training result (needs more discussion)

**Comment by kristapratico** [comment]
Spun off new issues for anything pending, closing this issue
