### ISSUE TITLE
EventGrid - Sprint 2 - Prototyping EventGrid Python Track2

### ISSUE THREAD

**Issue by t-swpill** [Azure/azure-sdk-for-python#11958]
Rampup

- [x] Familiarize existing champion scenarios/main customer requirements outlined by the Event Grid team (https://github.com/Azure/azure-sdk/issues/1405)

Implementation

- [ ] Add SAS authentication to Python client SDK
- [ ] Create code samples for the generated Python client SDK to meet main customer requirements/champion scenarios
- [ ] Explore which of these changes can be auto-generated by the swagger
- [ ] Update swagger to carry out these changes
- [ ] Test changes
- [ ] Update champion scenarios as needed to include code samples

Design

- [ ] Meet with Arch Board and revise client as discussed to gain approval

Deliverables

- [ ] Python code samples for champion scenarios
- [ ] Updated swagger
- [ ] Tests for code samples
