### ISSUE TITLE
Release Service Bus Track 2 Library Preview 4 for Python

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#11960]
**Design**
* [x] AMQP Data types
* [x] Plugins
* [ ] ATOM API Integration
* [ ] (stretch) Transactions

**Implement**
* [x] ATOM api: topics, subscriptions, rules

**Misc**
* [x] UX study feedback
  * [x] Single/multiple message naming
  * [x] Timeout reconciliation
  * [x] Prefetch/batch size reconciliation
  * [ ] AutoRenew improvements
  * [x] Multiple-with
  * [x] Iterator design
* [x] Consistency review changes
* [x] Github Issue Triage
