### ISSUE TITLE
EventGrid - Sprint 3 - Prototyping EventGrid Python Track2

### ISSUE THREAD

**Issue by t-swpill** [Azure/azure-sdk-for-python#12393]
Design (1 week)

* Create Convenience Layer API and samples to meet the following champion scenarios/customer reqs. :
  - [x] publish EGEvent/CloudEvent to topics
  - [x] publish EGEvent/CloudEvent to domain topics (takes in the same params as custom topics)
  - [x] publish EGEvent/CloudEvent to partner topics (not needed for single users, only partners. same as custom topics)
  - [x] ~~publish EGEvent/CloudEvent to system topics~~ (may not be needed)
  - [ ] support publishing lists of events, whether through batching or otherwise
  - [ ] consume messages from all event handlers, including Functions, EventHub, Service Bus, WebHooks, and return a list of generic event type objects
  - [ ] allow user to create specific event type objects from these generic event type objects
  - [ ] Meet internally with team to gain approval, make changes as needed
  - [ ] Meet with Arch Board to gain approval, make changes as needed  

Implementation (1.5 weeks)

- [ ] Explore which of these convenience layer changes can be auto-generated by the swagger
- [ ] Update swagger to carry out these changes
- [ ] Implement all methods for all classes
- [ ] Generate all event type models from swaggers with Track 2 AutoRest

Testing (1 week)

- [ ] Test existing Track 2 generated client, to start from a functional testing environment
- [ ] Add tests for all the new convenience layer changes
