### ISSUE TITLE
Release Event Hubs August 2020 update for Python

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#12426]
This is a parent issue tracking the work planned for Event Hubs for the August 2020 update.
Code complete date: July 31st, 2020

## API design 
- [ ] Use autorest to generate code for schema registry, decide package, client naming, etc. #12559 

## Features
- [ ] Idempotent event hub producer. #12428 

## Test
- [x] Remove Event Hubs live test dependency on ServiceBus SDK #12429

**Comment by YijunXieMS** [comment]
Schema registry PR is #12614 
Idemponent producer is still being designed
