### ISSUE TITLE
Opinion Mining Text Analytics Python Epic

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#12473]
- [x] Regenerate v3.1-preview.1: https://github.com/Azure/azure-sdk-for-python/issues/12474
- [x] Clear final design with architect: https://github.com/Azure/azure-sdk-for-python/issues/12475
- [x] implement design: https://github.com/Azure/azure-sdk-for-python/issues/12476
- [x] tests: https://github.com/Azure/azure-sdk-for-python/issues/12477
- [x] samples: https://github.com/Azure/azure-sdk-for-python/issues/12478
