### ISSUE TITLE
Release Service Bus Track 2 Library Preview 6 for Python

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13019]
Note: These items subject to change post cross-language sync and priority alignment. 

**Design**
* [ ] Discuss non-message send()
* [ ] Discuss concerns re: etag opt-in consistency
* [x] Discuss _utc on mgmt datetime properties.
* [ ] Discuss Is_live expired guards (local validation)
* [x] Discuss allowing a message to be sent twice
* [x] Settle on get_streaming_message_iter name
* [x] Discuss Authenticationerror failure mode change with service team
* [ ] (stretch) Send overload with session_id/schedule_time_utc
* [ ] (stretch) Transactions
* [ ] (stretch) Discuss session receiver unification with broader group.

**Implement**
* [x] Complete RuntimeInfo migration
* [ ] Complete client side validation consistency review
* [x] Complete api surface area consistency review
* [x] Continue exception surface area cleanup (e.g. Mode invalid param-> TypeError) and message naming consistency.
* [x] Closing a parent client should close children
* [ ] update_ methods should take keyword parameter overrides.
* [ ] (stretch) Reconnect on service outage. (may require conversation with service team to emulate for testing.)

**Misc**
* [ ] Distributed tracing readiness.
* [x] Doc generation warning and apistubgen warning cleanup
* [ ] Ensure object-accepting methods also accept dict-like.
* [ ] Normalize aio inline typing while expanding kwargs.
* [ ] Broad docstring cleanup (ensure all params documented, whitespace, urls if we decide those are worthwhile)
* [ ] Pre-release hardening/stress testing.

Note: Priority pivot midway through sprint, core items included:
- Combine dead letter receiver into sub_queue parameter of get_queue_receiver
- expose amqp message properties via inner object
- Broad data-plane-management (administration) name changes
- sas signature support

**Comment by KieranBrantnerMagee** [comment]
For posterity: Architect concerns about surface area and some contracts pushed GA off slightly, turning this release to Preview6.
