### ISSUE TITLE
[Schema Registry] Release SchemaRegistry Preview 1

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13048]
**Core Implementation**
- [x] SchemaRegistryClient
  - [x] register
  - [x] get schema_id
  - [x] get schema
- [x] SchemaRegistryAvroSerializer
  - [x] serialize
  - [x] deserialize
- [x] Test
  - [x] livetest
  - [x] unittest
  - [x] integration test with SB/EH
- [x] Samples
- [x] Doc

**Eng**
- [x] new livetest/ci pipeline for SchemaRegistryAvroSerializer

**Comment by yunhaoling** [comment]
released:
https://pypi.org/project/azure-schemaregistry/
https://pypi.org/project/azure-schemaregistry-avroserializer/
