### ISSUE TITLE
October Release of Key Vault for Python

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#13515]
### Features
 - [x] Local Crypto support
 - [ ] ~Secure Key Release design and implementation~
 - [ ] ~Arch Board review for Secure Key Release~
 - [x] Expose status methods for LRO backup/restore methods
 - [ ] API unification meeting
 - [x] Setup CI tests for Admin package
 - [x] Address customer feedback
 - [ ] ~[stretch] Move to ChallengeBasedAuth once it is in Core.~
 - [ ] ~[stretch] Id Parsing~
