### ISSUE TITLE
[Schema Registry] Release SchemaRegistry Preview 2

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#13685]
- Design
  - [ ] EH + serializer integration
  - [ ] async serializer support
  - [ ] multiple avro impl support
  - [ ] namespace pkg
  - [ ] broader discussion: how other sdks would use serializer/moving into azure core
- Investigation
  - [ ] Protobuf investigation
- Misc
  - [ ] Doc improvement
  - [ ] EH Integration Sample
