### ISSUE TITLE
Azure Cognitive Search October Release

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#13723]
- [x] Advanced batching support
- [x] Regenerate based on latest swagger
  - [x] Scoring profile
  - [x] IndexParameter
- [x] Add odata filter expression helpers
- [ ] More samples

**Comment by xiangyan99** [comment]
Released
