### ISSUE TITLE
[ServiceBus] Release ServiceBus 7.0.0b7

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#13744]
Note: This may either be GA or b7 depending on cross-language concerns and architectural signoff.  TBD.

**Feature work:**
- [x] (blocker) Make proposal for connstr builder
- [x] (blocker) AMQP bugs
- [x] (blocker) Complete client side validation consistency review
- [x] (blocker) Client invalid connection fail-on-open
- [ ] Failure reconnection hardening
- [ ] Distributed tracing readiness

**Maintenance:**
- [ ] (MQ) Fix the preparer "resource does not exist" issue
- [ ] (MQ) Test perf improvements (two parallel ways to approach it: dedup tests, minimize timeouts)
- [x] Doc warnings https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/810
	
**Open Questions and Design:**
- [x] (blocker) Assess renaming/object passing semantics of mgmt calls (e.g. topic -> topic_name)
- [x] (blocker) Should get/set session state unify with taking +returning bytes or strings?
- [ ] Rename amqp_message to amqp
- [ ] AutoLockRenew => AutoLockRenewer?
- [x] Use :rtype:/:returns: None for non-returning functions?
- [ ] Should we remove the is_live expired guards (clock skew failure mode)
- [ ] Rename logging_enable, since it's not really "all logging"
- [x] Prefix errors with "ServiceBus*"? (and "error" naming)
- [ ] Settle on get_streaming_message_iter name. (proposal: get_message_stream; need to compare precedent.)
- [ ] EntityAvailabilityStatus enum naming
- [ ] Non-message send() behavior
- [ ] Concerns surrounding etag opt-in consistency between sdks. (e.g. us and storage)

**Stretch Goals**
- [ ] Move backlog items (doc cleanup, intellisense cleanup, etc) into sprint and begin burning down.
