### ISSUE TITLE
[Metrics Advisor] Release metricsadvisor beta 1

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#14091]
## Feature implementation

- [x] [Metrics Advisor] implement DataFeed functionality
- [x] [Metrics Advisor] implement AnomalyAlertingConfiguration functionality
- [x] [Metrics Advisor] implement AnomalyDetectionConfiguration functionality
- [x] [Metrics Advisor] implement Alerting querying methods
- [x] [Metrics Advisor] implement Detection querying methods
- [x] [Metrics Advisor] implement Feedback methods
- [x] [Metrics Advisor] implement Hook methods
- [x] [Metrics Advisor] implement IngestionStatus methods
- [x] [Metrics Advisor] implement Metric methods

## Infrastructure

- [x] [Metrics Advisor] Initial commit to feature branch
- [x] [Metrics Advisor] Add CI build pipeline
- [ ] [Metrics Advisor] enable live test pipeline

## Doc

- [x] [Metrics Advisor] Create/improve readme
- [x] [Metrics Advisor] Ensure proper reference docs for public API surface

## Samples

- [x] [Metrics Advisor] create samples

**Comment by kristapratico** [comment]
Released! https://pypi.org/project/azure-ai-metricsadvisor/
