### ISSUE TITLE
November relese of Key Vault for Python

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#14233]
# Features

- [ ] Secure key release
- [ ] Local cryptography (as many algorithms - including new - as possible)

# Testing

- [ ] RBAC
- [ ] Backup/restore
- [ ] Secure key release
- [ ] Local cryptography

**Comment by lmazuel** [comment]
Not accurate anymore
