### ISSUE TITLE
Opentelemetry exporter for Azure Monitor December 2020 release

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#14270]
- [ ] https://github.com/Azure/azure-sdk-for-python/issues/14273
- [ ] https://github.com/Azure/azure-sdk-for-python/issues/14272
- [ ] https://github.com/Azure/azure-sdk-for-python/issues/14271
- [ ] https://github.com/Azure/azure-sdk-for-python/issues/14274

**Comment by rakshith91** [comment]
released beta1https://pypi.org/project/microsoft-opentelemetry-exporter-azuremonitor/
