### ISSUE TITLE
[Test][Epic] Create unified python test onboarding guidelines and coalesce around them.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14294]
**Goals**
This issue will track the work to do the following high level goals.
1. Create a set of documentation for onboarding onto and writing proper tests for azure-sdk-for-python.
2. The steps necessary to allow SDK owners to coalesce their libraries to the guidance decided in 1.
3. Any work arising from 2 that occurs as needed. (e.g. framework instability, additional features, etc, preventing coalescing)

Bullets, subtasks etc should be free to be created and modified as needed, as the early steps of this process are highly discovery-oriented.

**Phase 1 action items:**
- [ ] Create a home for the interim doc.
- [ ] Define "from 0" test rampup steps in the new doc, noting gaps.
- [ ] Define conceptual, semantic goals for "test acceptance."  (runtime, flakiness, unit/integration split, etc).
- [ ] When document is solid, share with SDK owners for feedback and to gather deltas-to-conformance.

**Phase 2 action items:**
TBD

**Phase 3 action items:**
TBD

**Comment by dave-read** [comment]
Does the target audience for this include external consumers of the SDK?  We have migrations from AWS where the teams are familiar with the [moto](http://docs.getmoto.org/en/latest/docs/getting_started.html) framework for unit testing and can't find something similar for Azure SDKs.  There are some [older issues](https://github.com/Azure/azure-sdk-for-python/issues/1031)  pointing external users to how SDK teams do their testing, but nothing that I can find that clearly points to end-to-end unit testing guidelines/samples for external consumers of the Python SDK.

**Comment by seankane-msft** [comment]
@dave-read These guidelines are a target for the library developers, although there may be helpful points for you and other external customers doing end-to-end testing. There is no Azure counterpart to moto, nor one on the roadmap afaik. For our own test infrastructure we use [vcrpy](https://vcrpy.readthedocs.io/en/latest/) to mock our HTTP transactions. vcrpy is not as comprehensive/specialized as moto, but it is a tool that can enable you to build out your end-to-end unit testing framework. Please let me know if this answer yields more questions than answers.

**Comment by lmazuel** [comment]
Closing, since doc is in PR now
