### ISSUE TITLE
[ServiceBus][Epic] Release ServiceBus 7.0.0 GA

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14332]
**Open Questions and Design:**
- [x] AutoLockRenew => AutoLockRenewer?
- [x] Should we remove the is_live expired guards on message settlement functionality? ( or address clock skew failure mode at the 5 minute edge) (Likely should; test if underlying error is cogent)
- [x] Should we rename logging_enable, since it's not really "all logging" (enable_amqp_frame_logging or something to that effect?)
- [x] Settle on get_streaming_message_iter name. (proposal: get_message_stream; need to compare precedent.)
- [x] EntityAvailabilityStatus enum naming; should it just be AvailabilityStatus to mirror the parameter name?
- [ ] Concerns surrounding etag opt-in consistency between sdks. (e.g. us and storage)
- [x] Should receive max wait time 0 mean immediate or error?
- [x] Are we OK with adding Message init gates for invalid types? (the existing errors are a bit opaque)
- [x] Should we allow None messages? They work.  Why do we disallow?
- [ ] Should (message property) scheduled_enqueue_time_utc and similar getters return an error if properties is null, or return null? (for setter, emplace it.) E.g. should mirror time_to_live or not?
- [ ] For footer/delivery annotations, bytes vs. string params?  (strings silently don't propogate currently, do we want a better failure behavior?)
- [x] Normalize amqp_message name with other sdks (amqp_annotated_message), keep, or just make "amqp"?
- [x] Do we want AutoLockRenew to halt itself when a session is closed voluntarily? (This probably applies to normal receivers via message renewal as well? Basically, what about our 'fallback' mechanism to allow settlement even after close?)

**Pre-release hardening:**
- [x] Flesh out stress tests (Full enumeration and min bar provided courtesy of @HarshaNalluru)
- [ ] Do a pass over logging, be generous.
- [ ] Pass over all docstrings.  Typedefs? retvals/returns descriptions? Mentions errors thrown?
- [x] Massive pass over all docs themselves. Gaps?  Migration guide comprehensiveness?
- [x] Bug bash.

**Feature work:**
- [x] Distributed tracing readiness
- [x] Prefix ambiguous errors with "ServiceBus*" (and "error" affixing)
- [x] Debug why this does not work, it should https://github.com/Azure/azure-sdk-for-python/issues/13873
- [x] Attempt to deprecate servicebussession, see if there's a way to not break docs/intellisense (+pycharm) even without an export.
> Min bar above for release blockers.
- [ ] Failure reconnection hardening
- [ ] Ensure tasks for taking dict object/flattened update args todos.

**Stretch Goals/Maintenance**
- [x] Move backlog items (doc cleanup, intellisense cleanup, etc) into sprint and begin burning down.
- [ ] (MQ) Fix the preparer "resource does not exist" issue
- [ ] (MQ) Test perf improvements (two parallel ways to approach it: dedup tests, minimize timeouts)
