### ISSUE TITLE
[Epic] [MetricsAdvisor] February 2021 release

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#16180]
- [x] Add aad support (#14085)
- [x] Add support for credential rotation (#14075)
- [x] Update methods return None (#16502)
- [x] Rename list_dimension_values (#16292)
- [x]  Change DataFeed.metric_ids from list to dict (#16479)

**Comment by xiangyan99** [comment]
Released
