### ISSUE TITLE
[EG arch feedback] Task list

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#16433]
- [ ] Kill Custom Events
- [ ] Kill Deserializer
- [ ] Cloud Event make data optional
- [ ] Support Data / data_base64 (not both)data must be optional ; data_base64 is optional too data can be bytes(convert to data_base64) data and data_base64 at the same time raises.
- [ ] SystemEventMappings to SystemEvents
- [ ] change order of EG event
