### ISSUE TITLE
March release of Key Vault for Python

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#16546]
## Features

- [x] RBAC including custom role definitions
- [x] Full/selective backup/restore
- [x] AES key support
- [x] Public exponent authoring for RSA keys

## Tasks

- [x] Documentation
- [x] Performance tests (pending further alignment)
- [x] ~Archboard API review for upcoming GA~ Review APIs in March
