### ISSUE TITLE
Azure.Identity Improvements for Python (June - October 2021)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#17217]
# Azure.Identity June - October 2021 Releases

### **Design:** Beta-1 Features

1.  **Feature: Support Tenant Id Challenges / Hints [tenant-hint.md](https://gist.github.com/christothes/34b713a70aad4e94f228b5a9b64f92a4)**
    - Support Key Vaults across multiple tenants
    - Address common issues when customers use VS/VSCode credentials with multiple credentials signed in
    
2.   **Feature: Add support for Managed Identity regional AAD authentication endpoints [#20027](https://github.com/Azure/azure-sdk-for-net/issues/20027)**
    - The [guidance] from the Azure IAM wiki for service teams using MI is to authenticate using a regional endpoint (e.g. `https://eastus2euap.login.microsoft.com`). However, the MSAL example given in the wiki uses APIs that are not currently exposed/used by [MsalConfidentialClient], namely `WithAuthority(Uri, bool)` and `WithInstanceDicoveryMetadata(string)`.
    - Today, when using the regional AAD endpoint with Azure.Identity (using a [ClientCertificateCredential]), we see an error `Application error - the login request was malformed and could not be matched with an existing authentication endpoint or instance.` The error goes away when using a global endpoint (`https://login.microsoftonline.com/`). 

3.   **Feature: Support overriding MSI_ENDPOINT for dev-time debugging for the Azure Kubernetes Service team [#670](https://github.com/Azure/azure-sdk-pr/issues/670)**
    - The Bridge to Kubernetes enables a user to natively debug one microservice on their local machine when "bridged" to other microservices running in Kubernetes.  AKS is looking for an environment variable that can be overridden to specify a custom managed identity endpoint. This is required so that when the user's locally running code tries to call the managed identity endpoint for a token, they are able to intercept it and redirect the call to the cluster so that the token can be fetched from the endpoint on the cluster.   

4.  **Feature:  Allow Pre-populated account name in browser during interactive login [#16983](https://github.com/azure/azure-sdk-for-net/issues/16983)**
    - Draft C# PR: https://github.com/azure/azure-sdk-fornet/pull/21082

5.  **Nickel Community Feature Requests related to StaticTokenCredential / token helper methods**
   - [ ] **Feature: Expose Credential type for DefaultAzureCredential and ChainedTokenCredential**
    - Enables users know which credential type is being used. [#8948](https://github.com/Azure/azure-sdk-for-net/issues/8948)
   - [ ] **Feature: Add new StaticTokenCredential type ([prototype PR](https://github.com/jongio/azidext/pull/41))**
    - Encapsulate an AAD credential with a prefetched token for an AAD application.
   - [ ] Request: Add support for fetching an access token from a refresh token
   - [ ]  Request: provide the functionality of building a token credential from (a: existing credential, b: tenant id) for refresh token based credentials: InteractiveBrowserCredential and DeviceCodeCredential, VisualStudioCodeCredential ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))
   - [ ]  Request: provide the functionality of setting tenant id for AzureCliCredential ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))
   - [ ]  Request: provide a valid token in VisualStudioCodeCredentialBuilder without tenant id, use this token we can list the tenants ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))
   - [ ]  Request: provide the functionality of listing cached account(azure environment, tenant id, user name, client id) for SharedTokenCacheCredential ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))

### **Code:** Beta-1 Features
1. Support Tenant Id Challenges / Hints
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/20302
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22353
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19300
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15797
2. Add support for Managed Identity regional AAD authentication endpoints
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/20027
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22355
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19301
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15798
3. MSI_ENDPOINT override via an API for the AKS team
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/21938
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22356
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19303
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15799
4. Allow Pre-populated account name in browser during interactive login
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/16983
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22359
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19305
    - JS:https://github.com/Azure/azure-sdk-for-js/issues/15802

### **Design:** Beta-2 Features
1.  **Feature: Add On-Behalf-Of (OBO) Auth Flow for the Microsoft Graph Team [tracking issue](https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/132)**
    - The [OAuth 2.0 On-Behalf-Of flow (OBO)](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow) serves the use case where an application invokes a service/web API, which in turn needs to call another service/web API. The idea is to propagate the delegated user identity and permissions through the request chain. For the middle-tier service to make authenticated requests to the downstream service, it needs to secure an access token from the Microsoft identity platform, on behalf of the user.
    - Prototype: https://github.com/jongio/azidext/pull/41

2. **Feature: Create AzureApplicationCredential for the MS Graph Team [#20364](https://github.com/Azure/azure-sdk-for-net/issues/20364)**

### **Code:** Beta-2 Features
1. Create AzureApplicationCredential
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/20364
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22366
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19309
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15805

## September Release Cycle - Beta-3 Feature Development

1. On-Behalf-Of (OBO) Auth Flow Support
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/21941
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22363
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19308
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15804

2. Support exchanging k8s token to AAD token
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/21939
    - Java:https://github.com/Azure/azure-sdk-for-java/issues/22358
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19304
    - JS:https://github.com/Azure/azure-sdk-for-js/issues/15800

3. Community Feature Requests related to StaticTokenCredential / Token convenience methods
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/21940
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22361
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19306
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15803

## October Release Cycle  - GA Release
1. Final Review of README.md / Quick Starts / Samples / Documentation for cross-language consistency
    - Emphases on updating sections for new features and champion scenarios
    - C#: https://github.com/Azure/azure-sdk-for-net/issues/21943
    - Java: https://github.com/Azure/azure-sdk-for-java/issues/22367
    - Python: https://github.com/Azure/azure-sdk-for-python/issues/19310
    - JS: https://github.com/Azure/azure-sdk-for-js/issues/15806

## November Release Cycle  - **Buffer**

# Related Work Items
- .NET - https://github.com/Azure/azure-sdk-for-net/issues/19404
- Java - https://github.com/Azure/azure-sdk-for-java/issues/19734
- Python - https://github.com/Azure/azure-sdk-for-python/issues/17217
- JS - https://github.com/Azure/azure-sdk-for-js/issues/14210
