### ISSUE TITLE
Update Identity README and MS Docs

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-python#17463]
Identity README Changes:
- [x] Update the DAC description to look like [this](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#defaultazurecredential). (#17777)
- [ ] ~Add Detailed Identity examples in the wiki for Identity Scenarios mentioned [here](https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Identity-Examples) and reference the link to the wiki in the README as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#examples).~
- [x] Add Configuration, examples reference links to Credential classes tables as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#credential-classes). (#17777)
- [x] Update the Next Steps to reference the libraries in azure-SDK repos as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#next-steps). (#17777)
- [x] Add Managed Identity Support section as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#managed-identity-support). (#17777)

MS Docs Change:
- [x] Update Azure SDK for Python Identity MS Docs to contain the content as [here](https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity).
