### ISSUE TITLE
[translation] user study + renames

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#17483]
Action items:

- [x] Reconsider the main scenario for translation and whether it should instead return a poller. If the P90 <= 2 docs and time from submission to completion <15 sec then an LRO makes sense. Understand from service team why the service is optimized for queueing many jobs/documents since this does not fit the common use case stated. Note that if we make this change, some of the below items are obsolete. Issue: https://github.com/Azure/azure-sdk-for-python/issues/17915
- [x] rename `DocumentStatusResult.translate_to` --> `translated_to`
- [x] ~~Improve documentation for `create_translation_job`. This should include info about how it starts the job but that `wait_until_done` must be used to complete the job~~
- [x] ~~Rename variables in samples that say `job_result`. This result suffix made people think the job was already finished~~
- [x] Fix the ItemPaged references in docs so that they show that it's an `ItemPaged[DocumentStatusResult]` etc
- [x] Check that we have a link in the README that links to the service docs about how to create the SAS URLs
- [x] Reconsider the model names `TranslationStatusResult` and `DocumentStatusResult`. People saw "status" in the name and assumed that a string was returned, not an object. Tracked in https://github.com/Azure/azure-sdk-for-python/issues/19257
- [x] Overload the input to `create_translation_job` to be more friendly in the single document scenario. Effectively option 1 in this issue: https://github.com/Azure/azure-sdk-for-python/issues/17916
- [x] Reconsider the naming of `inputs` to `begin_translation`. Perhaps this should be `actions` to align with TA and then the input object, `DocumentTranslationInput` should be called something like `DocumentTranslationAction`.
- [x] ~~Reconsider the utility of `has_completed`. People thought that this attribute would get updated when accessed, when reality it's just doing a completion check on the status strings~~
- [x] For the "starting translation, listing documents immediately, and getting an empty list b/c docs in container have not been enumerated" problem - start by improving docs for now...
