### ISSUE TITLE
[core] rest layer tracking issue

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#17538]
- [x] added `HttpRequest`
- [x] added `HttpResponse` and `AsyncHttpResponse`
- [x] added test suite (focusing on encoding, str, bytes)

Post WebPubSub release
- [ ] sniff for content type
- [ ] Accepts list of tuples for query, headers etc. (@johanste new formatting code should be able to help with some of this)
- [ ] Maybe add `read()` and `aread()` onto `HttpRequest` so users can see the content of their body, regardless of whether they're passing a stream
- [ ] Make `HttpResponse` a real context manager
- [ ] Add `iter_lines()` etc ways to read the response stream
- [ ] Auto fill `Content-Length`, `Content-Type`, `Transfer-Encoding` in response headers?

**Comment by johanste** [comment]
I assume that the auto fill was for request headers?

**Comment by iscai-msft** [comment]
@johanste `httpx` actually does response header auto-filling, that's waht I was referring to https://github.com/encode/httpx/blob/master/httpx/_models.py#L945

**Comment by iscai-msft** [comment]
closing in favor of LLC epic https://github.com/Azure/autorest.python/issues/887
