### ISSUE TITLE
Run mypy in Key Vault CI

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#19158]
Fix current errors and add packages to [mypy_hard_failure_packages.py](https://github.com/Azure/azure-sdk-for-python/blob/master/eng/tox/mypy_hard_failure_packages.py):
- [x] azure-keyvault-administration (#19246)
- [x] azure-keyvault-certificates(#20525)
- [x] azure-keyvault-keys(#20545)
- [x] azure-keyvault-secrets(#20507)

**Comment by mccoyp** [comment]
For reference: to run mypy for a package (e.g. `azure-keyvault-certificates`), run
`mypy --exclude _generated --ignore-missing azure`
from the top of the package -- in this case, from `azure-sdk-for-python/sdk/keyvault/azure-keyvault-certificates`

**Comment by mccoyp** [comment]
Steps to resolve:

For each package:

1. Run mypy check
2. Resolve warnings
3. Once there are no warnings, add package to hard failures file

**Comment by YalinLi0312** [comment]
Fixed.
