### ISSUE TITLE
Nickel Community Feature Requests related to StaticTokenCredential / token helper methods

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#19306]
Tracking Item to review the top customer-requested enhancements from the previous semester.  We will prioritize this list and fit in as many as possible in the final coding milestone of this semester (After all must-have features are completed first).  See @g2vinay and @jongio 

Ex unordered short list:

   - [x] **Feature: Expose Credential type for DefaultAzureCredential and ChainedTokenCredential**
    - Enables users know which credential type is being used. [#8948](https://github.com/Azure/azure-sdk-for-net/issues/8948). Resolved via logging approach.
   - [x] ** Enable MSAL Logging #20473  Note: No configuration needed on azure identity sdk side.
   - [x] ~** Enable PII Logging #20474~ 
              Note: MSAL python doesn't support PII logging, debug mode logs sensitive info already: Status: Resolved.
           - [ ] ~**Log the username that Shared Token Cached Credential uses.~
   - [x]  ** Improve Azure Identity SDK Error Messages and logging details #20484
   - [x]  ~** Add Support for Client Id Env Var support in Managed Identity Credential. #20486~
   - [x] ** Support passing custom client id to DAC. #20487
   - [x] ** Add Samples Explaining How to use Chained Token Credential
           - Sample is Present in README.md
   - [x] ** Add Samples demonstrating implementing Token Credential directly with MSAL / ADAL #20488
   - [x]  Request: provide the functionality of setting tenant id for AzureCliCredential 
              - See comment: https://github.com/Azure/azure-sdk-for-js/issues/15803#issuecomment-890243509
              - added in #19602

**Comment by joshfree** [comment]
> ** Improve Azure Identity SDK Error Messages and logging details Improve Azure Identity SDK Error Messages and logging details  #20484
>  ** Add Samples demonstrating implementing Token Credential directly with MSAL / ADAL Add Samples demonstrating implementing Token Credential directly with MSAL / ADAL  #20488

@chlowell @xiangyan99 can you update these last two open items?

**Comment by xiangyan99** [comment]
We will move them to Oct milestone.
