### ISSUE TITLE
Azure Service Bus Commitments for Python (July 2021-March 2022)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#19460]
[Azure Service Bus](https://azure.microsoft.com/services/service-bus/) is a cloud messaging service with message queues and publish-subscribe topics.

The [azure-servicebus](https://pypi.org/project/azure-servicebus/) package provides the SDK for Python developers to write applications that use Azure Service Bus. Version 7 of this package follows the latest [guidelines for writing Python SDKs for Azure services](https://azure.github.io/azure-sdk/python_introduction.html) with the goal of being  a client library that is developer-friendly, idiomatic to the Python ecosystem, and as consistent across different languages and platforms as possible.

This issue tracks the work we have planned for this package for the duration of July - December 2021

### New features:
- [ ] Support incoming new features in Azure Service Bus
- [ ] Add support for MaxMessageSize for queues and topics in the ServiceBusAdministrationClient

### Testing improvements:
- [ ] Update stress tests to use the new infrastructure where we now containerize the tests and have automation to run the tests on a scheduled basis
- [ ] Update perf tests to use the perf test framework that will then allow them to be automated

### General improvements:
- Fix incoming customer reported issues
- Build Trouble Shooting Guides

**Comment by ramya-rao-a** [comment]
Re-opening as we are planning to re-use this issue to track the extended semester work
