### ISSUE TITLE
MQ Performance Improvements

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#21136]
Issues to fix:
- [ ] Blob download: https://github.com/Azure/azure-sdk-for-python-pr/issues/645
- [ ] List blobs: https://github.com/Azure/azure-sdk-for-python/issues/19755 and https://github.com/Azure/azure-sdk-for-python-pr/issues/646
- [ ] FileShare upload/download: https://github.com/Azure/azure-sdk-for-python-pr/issues/654
- [ ] Blob parallel uploads: https://github.com/Azure/azure-sdk-for-python-pr/issues/655
- [ ] Parallel operations can crash: https://github.com/Azure/azure-sdk-for-python/issues/16085 and https://github.com/Azure/azure-sdk-for-python/issues/16081

Framework improvements:

- [ ] Support AMQP SDKs: https://github.com/Azure/azure-sdk-for-python/issues/20948
- [ ] SSL validation flag: https://github.com/Azure/azure-sdk-for-python/issues/20816
- [ ] Support test proxy server: https://github.com/Azure/azure-sdk-for-python/issues/20774
