### ISSUE TITLE
Release Schema Registry GA

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#21175]
Updates:
- [x] run black formatting (issue #21176)
- [x] investigate async `functools.lru_cache` alternatives (issue #20709)

Documentation:
- [x] full pass over docstrings (issue #21177) 
- [x] full pass over logging (issue #21178)

Testing:
- [x] full pass over tests (issue #21176 )
- [x] #21200
- [x] generate code with latest swagger (issue #20661)
- [x] #21198
- [ ] #21199

Design:
- [x] design for catching Avro type leaks (issue #20818)
- [x] decide on payload envelope (#21180)
- [x] respect user type when deserializing (#21225)
- [x] confirm SchemaRegistry APIView with feature crew
- [x] confirm SchemaRegistryAvroSerializer APIVew with feature crew
