### ISSUE TITLE
Azure Schema Registry Avro GA

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#23290]
Updates:
- [x] #23316

Documentation:
- [x] full pass over docstrings/logging (issue #23292)

Testing:
- [x]  perf tests (#23289)
- [x] full pass over tests 

Design:
- [x] #23317
- [x] #23318
- [ ] cross language interop (#21199 )
