### ISSUE TITLE
[translation] arch board feedback

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#24618]
- [x] rename xxx_language_code -> xxx_language ([comment](https://apiview.dev/Assemblies/Review/3fe2d18bbf02471eae4fd292c0d5f36e#8a69e1e128da442bacc722a908414b83))
- [x] Move `results_per_page` to the by_page() or don't expose ([comment](https://apiview.dev/Assemblies/Review/3fe2d18bbf02471eae4fd292c0d5f36e#6116b5c104f342de80c821ebaf01cc95))
- [x] hide `from_continuation_token` from the docs ([comment](https://apiview.dev/Assemblies/Review/3fe2d18bbf02471eae4fd292c0d5f36e#604ecd431a3f4f51ac06dff0dd7afa22))
- [x] rename `documents_not_yet_started_yet` to drop the `yet` ([comment](https://apiview.dev/Assemblies/Review/3fe2d18bbf02471eae4fd292c0d5f36e#b68c4bd9c6da4a848ec72999767d585d))
