### ISSUE TITLE
[Eventhub + Servicebus] Stress Test To-Do List

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#26069]
- [x] Update stress tests in Main to use the new pg cluster
- [ ] Figure out how to get Values.yaml accessible in chart.yaml to avoid the giant logic tree we currently have in pyamqp-> this will be matrix generation
- [x] Look at metrics (Montior cpu usage etc.) naming, names are currently descriptions, and they should be more succinct 
- [x] Change Naming (see richard chat)
- [x] #26243
