### ISSUE TITLE
[EventHubs] pyamqp GA

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#26226]
Testing/Typing:
- [x] @swathipil - #26227
- [x] @kashifkhan - turn on and fix pylint: #25396
- [x] @swathipil - check all mypy/typing stuff: #25471
- [x] @l0lawrence - stress testing: #21201
- [x] Ask Anna + Rakshith - #26230
- [x] @swathipil - #26229
- [x] @kashifkhan - fix logging: #22835 

Features:
- [x] @kashifkhan - Investigate aiohttp for websocket: #24315
  - [x] ~Ask Anna about adding async keep_worker_alive: #24411~ fixed [here](https://github.com/Azure/azure-sdk-for-python/pull/24975/commits/bc5b47dba3b6e5e7422f2f625897526fd4440c09)
- [x] @swathipil - #26228
  - [x] @swathipil  - merge EH feature branch into main

- [x] @swathipil - amqp switch : #21246 

(Stretch goals:
- #25875
)
- #26868
