### ISSUE TITLE
Refactor our code to be py3-friendly

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#26893]
- [ ] Update type annotation
- [ ] Remove dependency on six
- [ ] Update Traceback usage
