### ISSUE TITLE
[ServiceBus&EventHub] merge pyamqp + todo items

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-for-python#30316]
- [x] remove _streaming_iter method from SB
- [x] copy over pyamqp from SB to EH + copy back any changes
 - keep alive thread might need modifying
- [x] update websocket client version in the exception + in dev_requirements.txt
- [x] merge Paul's tracing PRs for SB/EH
- [x] go through GH issues + close out any completed ones: https://github.com/Azure/azure-sdk-for-python/labels/Messaging?page=5&q=is%3Aopen+label%3AMessaging
- [x] update old GH issues with messages saying, "we've released recently with some big changes. Can you check if this issue still exists?"
