### ISSUE TITLE
Unify python sdk release management

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-python#4147]
- [x] Migrate Python Repo CI from Travis to DevOps
- [x] Rationalize Release Methodology (github release, etc)
- [x] Support Release of All Packages through DevOps
- [ ] Publish Code Coverage from DevOps
