### ISSUE TITLE
Release Service Bus Track 2 Library Preview 1 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#4265]
This is a parent issue tracking the work planned for Service Bus to release the first preview in March following the [Python Azure SDK guidelines](https://azure.github.io/azure-sdk/python_introduction.html) 
Code complete date: March 6th, 2020

API design
- [x] Revisit the client structure i.e the various entry points in the package

Features
- [x] Support Azure Identity like we did in Event Hubs
- [x] Support retry configurability on clients like we did in Event Hubs
- [x] Support Web sockets & proxy like we did in Event Hubs
- [x] Send message to Queue
- [x] Receive and settle message from Queue
- [ ] Receive and settle message from seesion enabled Queue

**Comment by yunhaoling** [comment]
azure-servicebus 7.0.0b1 is out: https://pypi.org/project/azure-servicebus/7.0.0b1/
