### ISSUE TITLE
Release Azure.Core Library Preview for Python

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#4766]
- [x] Session management
  - [x] Sharing a session between Azure libraries and other libraries
  - [x] Lifetime of session for implicitly created sessions
  - [x] Lifetime of clients
- [x] Instrumentation
  - [x] Logging
  - ~~[ ] Distributed tracing~~
- [x] Streaming
  - [x] Retry:able streams
  - [x] Asynchronous generator 
- [x] Callback hooks
  - [x] Logging
  - [x] Transform/capture raw responses
- [x] Proxy support
  - [x] Policy vs. “native” stack support
- [x] Azure library-wide configuration
  - [x] Environment variables
  - [x] Configuration file
  - [x] Global/shared configuration settings
- [x] Authentication/base credentials/identity
- [x] Pylint-clean
- [x] MyPy-clean
- ~~[ ] MyPy/Pylint enabled in ES~~
- [x] Documentation
- [x] Paging
- [x] Polling
- [x] azure-core test failure clean
- [x] autorest test failure clean

**Comment by AlexGhiondea** [comment]
Closing this as we have released the preview. We should create a new epic for the next preview.
