### ISSUE TITLE
On-Boarding Event Hub to Central Repo

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#4807]
This is to track the work involved in moving [EventHub SDK Python](https://github.com/Azure/azure-event-hubs-python) to the central Repo.

- [x] Code and tests migrated and building
- [x] Make sure tests are passing (no flaky tests)
- [x] Enable tests in CI
- [x] Migrating issues to the central repo
- [x] Update the old README file to point users to the new code location

**Comment by yunhaoling** [comment]
@AlexGhiondea 

Hey Alex, I've done all the items in the list.
I think we've finished On-Boarding Event Hub to Central Repo, so we can close this issue now.
