### ISSUE TITLE
Release KeyVault Track 2 Library Preview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#4859]
### Release
- [x] Validate package contents prior to publishing
- [x] Update docs with link to package
- [x] Ensure docs are available

### Secrets
- [x] API Design proposal ready
- [x] API Design approved
- [x] Code complete
    - [x] Sync client
    - [x] Async client
- [x] Integration with Azure.Identity
    - [x] Dependency on azure.core-http
    - [x] New APIs added 
- [ ] Test complete
    - [x] Infrastructure (ie. project ready)
    - [ ] Tests for all APIs
        - [ ] Live
            - [ ] Nightly run
            - [x] Local
        - [x] Recorded
        - [x] Running in CI
- [x] Doc complete
    - [x] Doc comments
    - [x] Readme following the guidelines
    - [x] Samples for HERO scenarios
    - [x] Document missing features vs Track 1
- [ ] Challenge based authentication (to run in any clouds)

### Keys
- [x] API Design proposal ready
- [x] API Design approved
- [x] Code complete
    - [x] Sync client
    - [x] Async client
- [x] Integration with Azure.Identity
    - [x] Dependency on azure.core-http
    - [x] New APIs added 
- [ ] Test complete
    - [x] Infrastructure (ie. project ready)
    - [ ] Tests for all APIs
        - [ ] Live
            - [ ] Nightly run
            - [x] Local
        - [x] Recorded
        - [x] Running in CI
- [x] Doc complete
    - [x] Doc comments
    - [x] Readme following the guidelines
    - [x] Samples for HERO scenarios
    - [x] Document missing features vs Track 1
- [ ] Challenge based authentication (to run in any clouds)
