### ISSUE TITLE
Release Event Hub Track 2 Library Preview 1

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#5028]
Goal

Release the Event Hub Track 2 library.

- [x] Repo Readiness (#5114, #5110  )
- [x] Docs and Samples Readiness (#5113 , #5112)
- [x] Track 2 Guidelines Requirements
   - [x] Authentication (#5101)
   - [x] Logging and Tracing (#5085)
   - [x] Error Hierarchy patterns (#5100)
   - [x] Async namespace (#5081 )
   - [x] Retry and cancellations (#5084)
   - [x] Context manager to open and close connection (#5098)
   - [x] Expose configuration settings in a config class (#5099) -- changed to use kwargs intead of config class
   - [x] Iterator-like interface to replace callback (#5102)
- [x] New features
    - [x] Websocket and proxy support (#5071, #5103, #5106)
    - [x] OAuth support (#5097, #5107)
    - [x] Get partition information (#5324)

**Comment by yunhaoling** [comment]
- released package on pypi: https://pypi.org/project/azure-eventhub/5.0.0b1/
- release notes: https://github.com/Azure/azure-sdk/blob/master/docs/release-notes/preview/summary-preview1-python.md
