### ISSUE TITLE
On-board CosmosDB to the Central Repo

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#5038]
Goal:

The code and tests are moved and are building in the central repo for current released library
- [x] Code move
- [x] Tests works (Live tests and emulator tests)
- [ ] MyPY and Pylint clean

The code and tests are moved and are building in the central repo for preview library
- [x] Code move
- [x] Tests works (Live tests and emulator tests)
- [ ] MyPY and Pylint clean
