### ISSUE TITLE
Release KeyVault Track 2 Library Preview 2 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#6036]
This tracks the work of releasing the KeyVault Track 2 Preview 2

### API Design ###
- [ ] Crypto in Keys
  - [x] Proposal ready (#6318)
  - [ ] Design approved
- [ ] Certificates API
  - [ ] Proposal ready
  - [ ] Design approved

### Features ###
- [ ] ~Add logging and diagnostics (#5924)~
- [x] Challenge based authentication (to run in any clouds) (#5784)
- [ ] Crypto support for keys 
  - [x] Crypto via the service
    - [x] Code complete
      - [x] Async methods
      - [x] Sync methods (#5648)
    - [x] Testing complete (#6319)
  - [ ] ~Crypto on the client~
    - [ ] ~Code complete (#6317)~
      - [ ] ~Async methods~
      - [ ] ~Sync methods~
    - [ ] ~Testing complete (#6320)~
      - [ ] ~Use the service as an oracle (roundtrip through the service)~
      - [ ] ~Cross platform static tests (encrypted with .NET, decrypt with ... )~
- [ ] ~Certificates API~
  - [ ] ~Code complete~
    - [ ] ~Sync client~
    - [ ] ~Async client~
  - [ ] ~Test complete~
    - [ ] ~Sync client~

### Docs ### 
- [ ] Samples
- [x] Readme updates
