### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 2 for Python

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#6115]
Goal: Release the second Preview for Track 2 of Event Hubs

#5028 tracked the work that was needed to ship the first preview for Event Hubs as part of Track 2.
This issue is to track the next preview release for the same.

**EventHub:**
- [x] Add create_batch method for creating batch event date within size limit: #6119 
- [x] Pass retry options info to the amqp link: #6139 
- [x] Stress/Perf test: #5104 

**uAMQP:**
- [x] AMQP Connection share: #5326

**Common guideline policy:**
- [x] Add configurable retry delay support (exponential and linear): #6141 
- [x] Add timeout for building connection/link: #6135 

**EventProcessorHost**
- [x] Apply python design guideline: #6278 #6311
- [x] EPH APIs redesign: #6310 #6312 #6313 #6314

**Comment by yunhaoling** [comment]
We've released azure-eventhub 5.0.0b2 on pypi.
https://pypi.org/project/azure-eventhub/5.0.0b2/
