### ISSUE TITLE
Release Azure.Identity Library Preview 2 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#6337]
This tracks the work for Azure.Identity preview 2

- [x] Gap Analysis of MSAL
- [x] Provide Feedback to MSAL Team and schedule updates
- [x] Finalize Azure.Identity footprint for SDK Preview
- [x] Investigate other authentication schemes we need to support (user auth, auth from shared token cache)
    - [x] User/password Authentication
    - [x] Interactive Authentication
    - [x] Device Code Authentication
