### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 2 for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#6356]
- [x] Spec for Distributed Tracing Produced @johanste 
- [x] Distributed Tracing Plugin / Context updated for Open Telemetry for Python @SuyogSoti 
- [x] Tracing Context propagated through each Track 2 HTTP-based Library @SuyogSoti 
   - [x] AppConfiguration
   - [x] Azure.Core
   - [x] Azure.Identity
   - [x] KeyVault
      - [x] keys
      - [x] secrets
   - [x] Storage
      - [x] queue
      - [x] blob - is only done for sync
      - [x] files
- [X] Python dev owner identified (for after Suyog's internship) cc: @lmazuel @bryevdv 

**Related**
- Preview 2 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6356
- Preview 3 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6596
- Preview 4 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6597

**Comment by joshfree** [comment]
Closing Epic tracking Distributed Tracing Preview 2 feature work
