### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 3 for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#6596]
**API Design**
- [x] **Preview 3** (AMQP) Spec for Distributed Tracing Produced @johanste @lmolkova 
   - [x] Spec Ready - https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#file-minimal_instrumentation-md
   - [ ] Spec approved by Azure SDK Arch Board
- [ ] **Preview3** OpenTelemetry AMQP support designed @lmolkova 
   - [ ] Spec Ready
   - [ ] Spec approved by OpenTelemetry Maintainers
- [x] **Preview3** Distributed Tracing Plugin Package Name Standardized @johanste 
      - Azure.Core.Tracing

**Feature Work**
- [x] **Unfinished from Preview2** Tracing Context propagated through each HTTP-based Track 2 Library
   - [x] AppConfiguration
- [ ] **Preview 3** OpenTelemetry is updated with AMQP Support
   - [ ] OpenTelemetry AMQP support implemented
   - [ ] OpenTelemetry Packages available for testing by Azure SDK team
   - [ ] Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry for each language
- [ ] **Preview 3** Tracing Context propagated through each Track 2 Library
   - [ ] KeyVault (Certificates)
   - [ ] EventHubs (amqp)
   - [ ] EPH (amqp)

**Documentation**
- [ ] **Preview 3** Samples, Snippets, and Documentation completed for Distributed Tracing with Track 2 SDK Previews

**UX**
- N/A for Preview 3

**Related**
- Preview 2 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6356
- Preview 3 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6596
- Preview 4 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6597
