### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 4 for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#6597]
**API Design**
- N/A for Preview 4

**Feature Work**
- [x] **Undone from Preview 3** rename plugin to azure.core.tracing
- [x] OpenTelemetry Python SDK available for testing by Azure SDK team (0.1.0 alpha available) https://github.com/open-telemetry/opentelemetry-python#installation
    - [ ] Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry
- [x] **Undone from Preview 3** Tracing Context propagated through each Track 2 Library
   - [x] KeyVault (Certificates)
   - [x] EventHubs (amqp)
   - [x] EPH (amqp)

**Documentation**
- [ ] **Undone from Preview 3** Samples, Snippets, and Documentation completed for Distributed Tracing with Track 2 SDK Previews

**Documentation**
- N/A for Preview 4

**CUT**
- [ ] **Preview 4** UX study (validate theory that tracing support in Azure SDK is extremely useful for diagnosing reliability issues)
- [ ] **Preview 4** Before the UX study, audit to make sure tracing is consistent across each language
- [ ] **Preview 4** React to UX study feedback

**Related** 
- Preview 2 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6356
- Preview 3 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6596
- Preview 4 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6597
