### ISSUE TITLE
Release Cosmos Track 2 Library Preview 3 for Python

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk-for-python#6686]
### API Design

- [ ] https://github.com/Azure/azure-sdk/issues/570

### Features

- [ ] Pylint/MyPy Clean
- [x] Add Azure core as Pipeline as transport layer (minimal refactoring)
    - [x] Support pipeline policies - specifically distributed tracing
    - [x] Support pipeline transport for making requests
    - [x] Update exception hierarchy with Core as base
- [ ] Add `from_connection_string` constructors to clients
- [ ] Make kwargs options consistent with a complete Azure Core pipeline (e.g. retry policy)
- [ ] Constructors should be made track2 compliant (using Credentials object, kwargs for config)
- [ ] Update paged responses to use new Paged protocol (may or may not include refactoring to use Core base classes)
- [x] Rename Database and Container with "Client"

### Docs
- [ ] Add documentation for flattened config objects as kwargs

### Ux Study
