### ISSUE TITLE
Release Cosmos Track 2 Library Preview 4 for Python

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk-for-python#6749]
- [x] 	Implement request timeout parameters
o	Avoid conflicts with “request timeout” – e.g. operation timeout
o	Rename request timeout to socket timeout
- [x]	Revisit retry policy as pipeline policy
o	Still under discussion
o	Transport level-retry
- [x]	Accept transport object in constructor kwargs

**Comment by annatisch** [comment]
Shipped
