### ISSUE TITLE
Release Azure.Identity Library Preview 4 for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#6781]
**API Design**
- [x] **Preview 4** Review Exception Patterns across languages (@schaabs)
- [x] **Preview 4** Review Authority Host Configuration and ensure consistency across Languages (@schaabs)

**Feature Work**
- [x] **Preview 4**  Authorization Code Flow support with MSAL https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
- [x] **Preview 4** Create a combination of Automated and Manual testing (postman, curl, etc documented steps)
   - [x] Define Positive/Negative/Stress SSO test cases (cross applications, cross browser tabs)

**Documentation**
- [x] N/A

**CUT**
- [x] **Preview 4** Design solution for publishing credentials to shared token cache for dev-time experience (@schaabs)
- [x] **Preview 4** Implement solution for publishing credentials to shared token cache
   - [x] Cross-Language-SDK testing to ensure the Shared Token Cache functions as expected (correct synchronization)

**Related**
   - [ ] Preview 4 for Python https://github.com/Azure/azure-sdk-for-python/issues/6781
   - [x] Preview 3 for Python https://github.com/Azure/azure-sdk-for-python/issues/6591
   - [x] Preview 2 for Python https://github.com/Azure/azure-sdk-for-python/issues/6337
   - [x] Preview 1 for Python https://github.com/Azure/azure-sdk-for-python/issues/5048
