### ISSUE TITLE
Release AzConfig Track 2 Library Preview 3 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#6787]
### API Review ###
- [x] Proposal ready
- [ ] Design approved

### Features ###
- [ ] Integrate authentication from azure-identity
- [ ] React to swagger changes from the service team
- [ ] React to arch board feedback

### Docs ###
- [ ] Samples
- [ ] Readme update
- [ ] Change Log

**Comment by xiangyan99** [comment]
Preview 3 released. We will keep track remaining issues in preview 5
