### ISSUE TITLE
Build code generator for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#6859]
**Features**
- [ ] Develop Autorest JSON-RPC server #7401 
- [ ] Migrate autorest.common to Python #7404
- [ ] Develop x-ms generic extensions #7403
- [ ] Develop x-ms-pageable #7402
- [ ] Develop x-ms-long-running-operation #7405
- [ ] Develop `--azure-arm=True` #7408
- [ ] Support [multi-api generation script](https://github.com/Azure/azure-sdk-for-python/blob/master/scripts/multiapi_init_gen.py) inside Autorest #7409
- [ ] Design shared multi-api support #7410

**Tests**
- [x] Convert gulp files to tox #7411
- [x] Port testserver launcher #7412
- [ ] Plug new CI #7413

**Comment by lmazuel** [comment]
Seems to me deprecated Epic
