### ISSUE TITLE
Release KeyVault Track 2 Library Preview 4 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#7084]
### Api Design ###
- [ ] Certificates API
  - [x] Proposal ready
  - [ ] Design approved

### Features ###
- [ ] Support for Storage client side encryption
- [ ] Address feedback for certificates APIs.
- [x] Exception handling cleanup
- [ ] Enable live tests
- [x] Rename model base classes
  - [x] i.e. Secret will have Value and Properties (or TBD)
- [x] Provide string representation for models
- [ ] ~Additional crypto API support~
  - [ ] ~Support multi-block crypto in Keys.~
- [ ] ~Add separate client for service crypto (#4834)~

### Docs ###
- [x] ReadMe updates
- [x] Change log

### User study ###
- [x] Planned
- [ ] Completed
