### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 4 for Python

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#7177]
For general summary & goal, please see: [Release Event Hub Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442) 

The work items linked to this issue herein represent the tasks needed to produce the 4th preview for the "track two" Event Hubs client library.

## API Design Review with the Board 
- [x] Create and send batch

## Features
- [x] Last Enqueued Event Info for Event Processor users #6140
- [x] 🏃 Remove explicit support for IotHub connection string

## Diagnosability
- [ ] Review existing logging story 
- [x] Tracing #6315

## Stress Testing
- [x] Set up basic send, receive operations in long running process across days to flush out bugs
- [x] Refer to Track 1 Stress Test framework in Python, .Net and Java to come up with proposal 
- [ ] 🏃 Work with Eng Sys team on Test framework for Track 2

**Comment by yunhaoling** [comment]
preview4 released
https://pypi.org/project/azure-eventhub/5.0.0b4/
https://pypi.org/project/azure-eventhub-checkpointstoreblob-aio/
