### ISSUE TITLE
Release Azure.Identity Library Preview 5 for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#7591]
**API Design**
- [x] **From Preview 4** Review Exception Patterns across languages for consistency (@schaabs)
- [x] **From Preview 4** Review Authority Host Configuration and ensure consistency across Languages (@schaabs)

**Feature Work**
- [ ] Fix remaining active issues (excludes Milestone=Backlog) https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Identity+no%3Amilestone

**Documentation**
- [x] N/A

**Related**
   - [x] Release Azure.Identity Track 2 (parent epic) Library https://github.com/Azure/azure-sdk/issues/536
   - [x] Preview 4 for Python https://github.com/Azure/azure-sdk-for-python/issues/6781
   - [x] Preview 3 for Python https://github.com/Azure/azure-sdk-for-python/issues/6591
   - [x] Preview 2 for Python https://github.com/Azure/azure-sdk-for-python/issues/6337
   - [x] Preview 1 for Python https://github.com/Azure/azure-sdk-for-python/issues/5048
