### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 5 for Python

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#7604]
**API Design**
- N/A

**Feature Work**
- [ ] Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry
- [ ] Zero Bug Bounce on active issues https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aissue+is%3Aopen+tracing+label%3AClient+label%3AMonitor

**Documentation**
- [ ] **Undone from Preview 3** Samples, Snippets, and Documentation completed for Distributed Tracing with Track 2 SDK Previews
- [ ] Update existing code samples for Storage, KeyVault, and EventHubs to include Distributed Tracing for OpenCensus and OpenTelemetry

**Related** 
- Release Distributed Tracing Track 2 Support https://github.com/Azure/azure-sdk/issues/501
- Preview 2 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6356
- Preview 3 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6596
- Preview 4 Tracing Epic for Python: https://github.com/Azure/azure-sdk-for-python/issues/6597

**Comment by Petermarcu** [comment]
@joshfree I see there are still two things tracked on this but all up, is this complete other than keeping up to take with the OpenTelemetry libraries progress?

**Comment by joshfree** [comment]
@Petermarcu yes, this is done.  I can close it on @lmazuel 's behalf.
