### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 6 for Python

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#8474]
Customer reported issues:
- [ ] #8404 eventhub: the program crashes if producer not use with `with`

Optimize for customers
- [x] #8585 Early release a partition from an EventHubConsumerClient if there is an exception
- [x] #8587 Set owner_level default value 0 instead of None
- [x] #8650 Change BlobPartitionManager constructor to prevent users rely on ContainerClient

Internal code refactor:
- [x] #8472 [EventHubs] Pull-model refactor
- [x] #8603 [EventHubs] Consolidate credentials object

Tests
- [x] #8476 [EventHubs] Increate test coverage and code testability
- [x] #8477 Event Hubs Stress/Long running/Perf Test for Track 2 GA
- [x] #8649 Migrate old pull model live tests to new customer-facing push model

API review and cross lang sync
- [x] #8535 Use small cases for path and blob meta data keys in checkpointstoreblob and -aio
- [x] #8536 Change for API review

**Comment by YijunXieMS** [comment]
Released 5.0.0b6 on 12/03/2019
