### ISSUE TITLE
Release Event Hubs Track 2 GA for Python

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#8954]
**Updates:**
- [x] Remove azure-common dependency (issue #8953)
- [x] [**In PR: #9045**] Opt-in to MyPy validation on CI (issue #8952)
- [x] [**In PR: #8918**] Clean up deprecated Message attributes (issue #8808)
- [x] Run Black formatting (issue #8992)

**Documentation:**
- [ ] Review whether manual docs TOC can be replaced with full auto-doc now that all internal modules have been underscore-prefixed (issue #8874)
- [x] Add more sample code (issue #9037)
- [x] Migration Guide from Track1 to Track2 (issue #9039)

**Testing:**
- [ ] Better unit test coverage.
- [x] Better user scenario testing (issue #9038)

**API review:**
Based on customer feedback, specifically review the API for:
- [ ] Sending single Events
- [ ] Processing batches of events in `on_event` callback

**uAMQP:**
- [x] Reported customer issue regarding 30min receive hang (issue #9017)
- [x] Review and test GC code PR [#115](https://github.com/Azure/azure-uamqp-python/pull/115) (including long running tests and shared connection tests) (issue #8404)
- [x] Release patch 1.2.5 (PR [#127](https://github.com/Azure/azure-uamqp-python/pull/127))

**Comment by YijunXieMS** [comment]
The following two APIs was excluded from GA. Enhancements may be made in some follow-up releases.
Sending single Events
Processing batches of events in on_event callback

**Comment by YijunXieMS** [comment]
azure-eventhub 5.0.0 released on 1/13/2020
https://pypi.org/project/azure-eventhub/5.0.0
