### ISSUE TITLE
Create Test Automation for Azure.Identity running in Azure Hosted Environments

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#9316]
**Epic: Create Test Automation for Azure.Identity running in Azure Hosted Environments**

- [x] Azure Cloud Shell
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions (#9336)
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/795
- [x] Azure VM
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions (#9354)
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/815
- [x] Azure Kubernetes
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions (#9495)
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/814
- [ ] Azure WebJobs
  - [ ] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [ ] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/902

**Comment by joshfree** [comment]
Updating issue as Functions and App Services has been moved to the backlog

**Comment by joshfree** [comment]
Moving this to the September milestone for wrapping up the WebJobs python-specific tests.  EngSys is working on supporting WebJobs test automation now, so getting this finished in the September milestone would be good timing.
