### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 2 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#9642]
This tracks the work to release the Azure Cognitive Search Track2 Preview 2 Library for Python

### Arch board
- [ ] Review user defined schemas (part 2)
  - [ ] ~FieldBuilder~

### Features
- [x] Service APIs
- [x] React to feedback from Preview 1 around document operations
- [x] Implement index management operations
- [x] Design and implement batching operation for document operations 
- [ ] ~*? Expose JSON serialization controls to the user (maybe not relevant to python)*~
- [x] Continuation tokens design
