### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 3 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#9643]
This tracks the work to release the Azure Cognitive Search Track2 Preview 3 Library for Python

### Arch Board
- [ ] ArchBoard review for batching
- [x] API review for Index operations

### Features
- [ ] FacetResults strong types (ranges, etc)
- [ ] Design and implement
  - [ ] Skillset
  - [x] Synonyms
- [ ] Design and implement batching operation for document operations 
- [ ] Design and implement 
  - [ ] Indexers
- [ ] Design and implement DataSources
- [ ] Cross language consistency meeting and API Review
- [ ] Address feedback from Arch Board / UX Study
- [ ] (?) Move spatial types to Azure.Core

### Docs
- [ ] Schedule UX study 
  - [ ] Define hypothesis
- [ ] Run UX Study

**Comment by bryevdv** [comment]
https://pypi.org/project/azure-search-documents/1.0.0b3/
