### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 4 for Python

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#9644]
This tracks the work to release the Azure Cognitive Search Track2 Preview 4 Library for Python

### Arch board
- [ ] Cross language consistency review
- [ ] Final API approval

### Features
- [ ] Live test setup
- [ ] API feedback updates

### UX Study
- [ ] Prepare for UX study
- [ ] Run UX study

### Docs
- [ ] Samples
