### ISSUE TITLE
March release of KeyVault for Python

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#9753]
# Features

- [x] Add new Soft Delete properties to Key Vault data plane (#9907)
- [x] KeyOperations needs to support "import" for 7.1-preview (#9930)

# Bugs

- [ ] ~Importing PEM-encoded certificates may not work (#9874)~

**Comment by chlowell** [comment]
These features are available now in 4.2.0b1
