### ISSUE TITLE
Release Event Hubs March 2020 update for Python

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#9795]
This is a parent issue tracking the work planned for Event Hubs for the March update.
Code complete date: March 6th, 2020

## API design 
- [ ] Propose smarter send APIs such that the user doesnt have to one by one fill the `EventDataBatch` to be able to send events
- [ ] Propose API to receive in batches
- [ ] Propose API to control greedy claiming of partitions by the Event Processor

## Features
- [ ] Code sample showing how to convert IotHub connection string to an Event Hubs compatible one which points to the built-in Event Hubs endpoint
- [ ] Receiver Redirect feature
- [ ] Review current logging experience, come up with a plan to streamline and be consistent across languages for ease of customer support, tackle low hanging fruits

## Testing
- [ ] Test Event Hubs and Storage Blob checkpoint store in Azure Stack

cc @YijunXieMS, @yunhaoling, @KieranBrantnerMagee
