### ISSUE TITLE
July release of KeyVault for Python

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#9866]
# Features

- [ ] (Preview) Support local key encryption for CryptographyClient (#9754)
- [ ] (Preview) Support Role-based Access Control (RBAC) for data plane (#9755)
- [ ] ~Allow customers to parse certificate, key, and secret IDs from URLs (#9908)~
